all: finalized

wkbench: clean
	ec -batch -ace windows.ace -freeze -c_compile

finalized: clean
	ec -batch -ace windows.ace -finalize -c_compile
	copy /Y EIFGEN\F_code\*.exe %OPENEHR%\oe_distrib\windows\adl_workbench\bin
	cd EIFGEN\W_code
	finish_freezing -silent
	cd ..\..

clean:
	del /q /s *.epr
	rmdir /q /s EIFGEN

