= Support and Contributing

== I have a problem...

===  with the ADL Workbench

You can report an issue on the openEHR {adl_workbench_prs}[AWB PR tracker^]. Please select the appropriate component, e.g. User interface, Validator, etc.

===  with an archetype

If it is a CKM archetype, and it really appears to be an error or deficiency, you can:

* Submit a comment to CKM, with the following steps:
** Go to {openehr_CKM}[CKM] and login
** Navigate to the archetype in the left hand explorer and select (double-click)
** Now right-click-Discussion.
* Discuss it on the {openehr_mailing_lists}[openehr-clinical mailing list^].

If it is an ADL2 test archetype, create a problem report on the Jira AWB PR tracker, with component set to 'Test archetypes'.

=== with this online documentation

If your problem is that you can't find an answer to what you are looking for, please report this on the Jira AWB PR tracker, with component set to 'Documentation'. If you really need an answer, don't be afraid to post on the {openehr_mailing_lists}[openehr-technical mailing list^].

=== with the openEHR specifications

Please visit the {projects/SPECPR}[dedicated Jira tracker^].

== How can I contribute?

You are already a saint for asking. Most likely your interest is in one of the areas of: clinical archetypes, ADL/AOM tooling, or specifications. Useful things you can do include the following.

=== I can help with clinical / demographic archetypes

If your interest is in building and/or reviewing the CKM archetypes, or you want to offer new archetypes to CKM, please either login to CKM and join existing discussions, and/or contact the CKM editors and/or start a discussion on the {openehr_mailing_lists}[openehr-clinical mailing list^].

=== I want to help improving ADL / AOM 2

The single most useful thing you can do is to help build up the {openehr_adl_archetypes_github}[test archetype Git repository^]. We need more archetypes to test more ADL2 use cases. Most of the validity conditions have at least one or two archetypes, but some conditions can be triggered by different kinds of archetypes. If you see you can post a message on the {openehr_mailing_lists}[openehr-technical mailing list^].

=== I can help improving the tool

The ADL Workbench is written in the Eiffel language ({openehr_awb_github}[Git repository^]). If you are interested in working on it, please indicate there.

A newer tool called Archie ({openehr_archie_github}[Git repository^]) in Java fully implements AOM2, ADL2, BMM and ODIN.

=== I would like to port the tool to another language

As a starting point, it is suggested you post an initial enquiry on the {openehr_mailing_lists}[openehr-technical mailing list^].