#
# this should work but does not
#
# DIRS = adl_validator adl_workbench test
# 
# $(DIRS): 
# 	pushd $@ & nmake -f makefile.windows & popd
# 
# all: $(DIRS)
# 

all: app1 app2 app3

app1:
 	pushd libraries & nmake -f makefile.windows & popd

app2:
 	pushd components & nmake -f makefile.windows & popd

app3:
 	pushd apps & nmake -f makefile.windows & popd
