indexing
	component:   "openEHR Archetype Project"
	description: "[
				 Types of compiler error generated by the archetype compiler.
				 ]"
	keywords:    "ADL"
	author:      "Thomas Beale"
	support:     "Ocean Informatics <support@OceanInformatics.biz>"
	copyright:   "Copyright (c) 2008 Ocean Informatics Pty Ltd"
	license:     "See notice at bottom of class"

	file:        "$URL$"
	revision:    "$LastChangedRevision$"
	last_change: "$LastChangedDate$"


class COMPILER_ERROR_TYPES

feature -- Definitions

	Err_type_valid: INTEGER is 0
	Err_type_parse_error: INTEGER is 1
	Err_type_validity_error: INTEGER is 2
	Err_type_warning: INTEGER is 3

feature -- Access

	Err_type_names: HASH_TABLE [STRING, INTEGER] is
			-- version of name suitable for screen display
		once
			create Result.make(0)
			Result.put("Parse errors", Err_type_parse_error)
			Result.put("Validity errors", Err_type_validity_error)
			Result.put("Warnings", Err_type_warning)
		end

	Err_type_pixmap_names: HASH_TABLE [STRING, INTEGER] is
			-- version of name suitable for use as file name
		once
			create Result.make(0)
			Result.put("parse_errors", Err_type_parse_error)
			Result.put("validity_errors", Err_type_validity_error)
			Result.put("warnings", Err_type_warning)
		end

feature -- Status Report

	valid_err_type (i: INTEGER): BOOLEAN is
			-- True if i is a valid error type
		do
			Result := i >= Err_type_valid and i <= Err_type_warning
		end

end


--|
--| ***** BEGIN LICENSE BLOCK *****
--| Version: MPL 1.1/GPL 2.0/LGPL 2.1
--|
--| The contents of this file are subject to the Mozilla Public License Version
--| 1.1 (the 'License'); you may not use this file except in compliance with
--| the License. You may obtain a copy of the License at
--| http://www.mozilla.org/MPL/
--|
--| Software distributed under the License is distributed on an 'AS IS' basis,
--| WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
--| for the specific language governing rights and limitations under the
--| License.
--|
--| The Original Code is compiler_error_types.e
--|
--| The Initial Developer of the Original Code is Thomas Beale.
--| Portions created by the Initial Developer are Copyright (C) 2008
--| the Initial Developer. All Rights Reserved.
--|
--| Contributor(s):
--|
--| Alternatively, the contents of this file may be used under the terms of
--| either the GNU General Public License Version 2 or later (the 'GPL'), or
--| the GNU Lesser General Public License Version 2.1 or later (the 'LGPL'),
--| in which case the provisions of the GPL or the LGPL are applicable instead
--| of those above. If you wish to allow use of your version of this file only
--| under the terms of either the GPL or the LGPL, and not to allow others to
--| use your version of this file under the terms of the MPL, indicate your
--| decision by deleting the provisions above and replace them with the notice
--| and other provisions required by the GPL or the LGPL. If you do not delete
--| the provisions above, a recipient may use your version of this file under
--| the terms of any one of the MPL, the GPL or the LGPL.
--|
--| ***** END LICENSE BLOCK *****
--|
