note
	description: "[
		Objects that represent an EV_TITLED_WINDOW.
		The original version of this class was generated by EiffelBuild.
		This class is the implementation of an EV_TITLED_WINDOW generated by EiffelBuild.
		You should not modify this code by hand, as it will be re-generated every time
		 modifications are made to the project.
		 	]"
	generator: "EiffelBuild"
	date: "$Date$"
	revision: "$Revision$"

deferred class
	MAIN_WINDOW_IMP

inherit
	EV_TITLED_WINDOW
		redefine
			create_interface_objects, initialize, is_in_default_state
		end
			
	GUI_CONSTANTS
		undefine
			is_equal, default_create, copy
		end

feature {NONE}-- Initialization

	initialize
			-- Initialize `Current'.
		do
			Precursor {EV_TITLED_WINDOW}
			initialize_constants

			
				-- Build widget structure.
			set_menu_bar (l_ev_menu_bar_1)
			l_ev_menu_bar_1.extend (file_menu)
			file_menu.extend (file_menu_open)
			file_menu.extend (file_menu_save_as)
			file_menu.extend (l_ev_menu_separator_1)
			file_menu.extend (file_menu_exit)
			l_ev_menu_bar_1.extend (edit_menu)
			edit_menu.extend (edit_menu_copy)
			edit_menu.extend (edit_menu_select_all)
			extend (explorer_split_area)
			explorer_split_area.extend (explorer_area)
			explorer_area.extend (l_ev_label_1)
			explorer_area.extend (explorer_tree)
			explorer_split_area.extend (main_split_area)
			main_split_area.extend (main_notebook)
			main_notebook.extend (source_text)
			main_notebook.extend (dadl_tree)
			main_split_area.extend (status_area)

			file_menu.set_text ("&File")
			file_menu_open.set_text ("&Open")
			file_menu_save_as.set_text ("&Save As")
			file_menu_exit.set_text ("E&xit")
			edit_menu.set_text ("&Edit")
			edit_menu_copy.set_text ("&Copy")
			edit_menu_select_all.set_text ("Select &All")
			explorer_split_area.enable_item_expand (explorer_area)
			explorer_split_area.disable_item_expand (main_split_area)
			explorer_area.disable_item_expand (l_ev_label_1)
			l_ev_label_1.set_text ("Tests")
			explorer_tree.set_minimum_width (150)
			main_split_area.enable_item_expand (main_notebook)
			main_split_area.disable_item_expand (status_area)
			main_notebook.set_item_text (source_text, "Source")
			main_notebook.set_item_text (dadl_tree, "Node map")
			status_area.disable_edit
			set_title ("Display window")

			set_all_attributes_using_constants
			
				-- Connect events.
			file_menu_save_as.select_actions.extend (agent exit_app)
			file_menu_exit.select_actions.extend (agent exit_app)
			edit_menu_copy.select_actions.extend (agent on_copy)
			explorer_tree.select_actions.extend (agent select_explorer_item)
				-- Close the application when an interface close
				-- request is recieved on `Current'. i.e. the cross is clicked.
			close_request_actions.extend (agent destroy_and_exit_if_last)

				-- Call `user_initialization'.
			user_initialization
		end
		
	create_interface_objects
			-- Create objects
		do
			
				-- Create all widgets.
			create l_ev_menu_bar_1
			create file_menu
			create file_menu_open
			create file_menu_save_as
			create l_ev_menu_separator_1
			create file_menu_exit
			create edit_menu
			create edit_menu_copy
			create edit_menu_select_all
			create explorer_split_area
			create explorer_area
			create l_ev_label_1
			create explorer_tree
			create main_split_area
			create main_notebook
			create source_text
			create dadl_tree
			create status_area

			create string_constant_set_procedures.make (10)
			create string_constant_retrieval_functions.make (10)
			create integer_constant_set_procedures.make (10)
			create integer_constant_retrieval_functions.make (10)
			create pixmap_constant_set_procedures.make (10)
			create pixmap_constant_retrieval_functions.make (10)
			create integer_interval_constant_retrieval_functions.make (10)
			create integer_interval_constant_set_procedures.make (10)
			create font_constant_set_procedures.make (10)
			create font_constant_retrieval_functions.make (10)
			create pixmap_constant_retrieval_functions.make (10)
			create color_constant_set_procedures.make (10)
			create color_constant_retrieval_functions.make (10)
		end


feature -- Access

	file_menu, edit_menu: EV_MENU
	file_menu_open, file_menu_save_as, file_menu_exit, edit_menu_copy,
	edit_menu_select_all: EV_MENU_ITEM
	explorer_split_area: EV_HORIZONTAL_SPLIT_AREA
	explorer_area: EV_VERTICAL_BOX
	explorer_tree, dadl_tree: EV_TREE
	main_split_area: EV_VERTICAL_SPLIT_AREA
	main_notebook: EV_NOTEBOOK
	source_text: EV_RICH_TEXT
	status_area: EV_TEXT

feature {NONE} -- Implementation

	l_ev_menu_bar_1: EV_MENU_BAR
	l_ev_menu_separator_1: EV_MENU_SEPARATOR
	l_ev_label_1: EV_LABEL

feature {NONE} -- Implementation

	is_in_default_state: BOOLEAN
			-- Is `Current' in its default state?
		do
			-- Re-implement if you wish to enable checking
			-- for `Current'.
			Result := True
		end

	user_initialization
			-- Feature for custom initialization, called at end of `initialize'.
		deferred
		end
	
	exit_app
			-- Called by `select_actions' of `file_menu_save_as'.
		deferred
		end
	
	on_copy
			-- Called by `select_actions' of `edit_menu_copy'.
		deferred
		end
	
	select_explorer_item
			-- Called by `select_actions' of `explorer_tree'.
		deferred
		end
	

feature {NONE} -- Constant setting

	set_attributes_using_string_constants
			-- Set all attributes relying on string constants to the current
			-- value of the associated constant.
		local
			s: detachable STRING_32
		do
			from
				string_constant_set_procedures.start
			until
				string_constant_set_procedures.off
			loop
				string_constant_retrieval_functions.i_th (string_constant_set_procedures.index).call (Void)
				s := string_constant_retrieval_functions.i_th (string_constant_set_procedures.index).last_result
				if s /= Void then
					string_constant_set_procedures.item.call ([s])
				end
				string_constant_set_procedures.forth
			end
		end

	set_attributes_using_integer_constants
			-- Set all attributes relying on integer constants to the current
			-- value of the associated constant.
		local
			i: INTEGER
			arg1, arg2: INTEGER
			int: INTEGER_INTERVAL
		do
			from
				integer_constant_set_procedures.start
			until
				integer_constant_set_procedures.off
			loop
				integer_constant_retrieval_functions.i_th (integer_constant_set_procedures.index).call (Void)
				i := integer_constant_retrieval_functions.i_th (integer_constant_set_procedures.index).last_result
				integer_constant_set_procedures.item.call ([i])
				integer_constant_set_procedures.forth
			end
			from
				integer_interval_constant_retrieval_functions.start
				integer_interval_constant_set_procedures.start
			until
				integer_interval_constant_retrieval_functions.off
			loop
				integer_interval_constant_retrieval_functions.item.call (Void)
				arg1 := integer_interval_constant_retrieval_functions.item.last_result
				integer_interval_constant_retrieval_functions.forth
				integer_interval_constant_retrieval_functions.item.call (Void)
				arg2 := integer_interval_constant_retrieval_functions.item.last_result
				create int.make (arg1, arg2)
				integer_interval_constant_set_procedures.item.call ([int])
				integer_interval_constant_retrieval_functions.forth
				integer_interval_constant_set_procedures.forth
			end
		end

	set_attributes_using_pixmap_constants
			-- Set all attributes relying on pixmap constants to the current
			-- value of the associated constant.
		local
			p: detachable EV_PIXMAP
		do
			from
				pixmap_constant_set_procedures.start
			until
				pixmap_constant_set_procedures.off
			loop
				pixmap_constant_retrieval_functions.i_th (pixmap_constant_set_procedures.index).call (Void)
				p := pixmap_constant_retrieval_functions.i_th (pixmap_constant_set_procedures.index).last_result
				if p /= Void then
					pixmap_constant_set_procedures.item.call ([p])
				end
				pixmap_constant_set_procedures.forth
			end
		end

	set_attributes_using_font_constants
			-- Set all attributes relying on font constants to the current
			-- value of the associated constant.
		local
			f: detachable EV_FONT
		do
			from
				font_constant_set_procedures.start
			until
				font_constant_set_procedures.off
			loop
				font_constant_retrieval_functions.i_th (font_constant_set_procedures.index).call (Void)
				f := font_constant_retrieval_functions.i_th (font_constant_set_procedures.index).last_result
				if f /= Void then
					font_constant_set_procedures.item.call ([f])
				end
				font_constant_set_procedures.forth
			end	
		end

	set_attributes_using_color_constants
			-- Set all attributes relying on color constants to the current
			-- value of the associated constant.
		local
			c: detachable EV_COLOR
		do
			from
				color_constant_set_procedures.start
			until
				color_constant_set_procedures.off
			loop
				color_constant_retrieval_functions.i_th (color_constant_set_procedures.index).call (Void)
				c := color_constant_retrieval_functions.i_th (color_constant_set_procedures.index).last_result
				if c /= Void then
					color_constant_set_procedures.item.call ([c])
				end
				color_constant_set_procedures.forth
			end
		end

	set_all_attributes_using_constants
			-- Set all attributes relying on constants to the current
			-- calue of the associated constant.
		do
			set_attributes_using_string_constants
			set_attributes_using_integer_constants
			set_attributes_using_pixmap_constants
			set_attributes_using_font_constants
			set_attributes_using_color_constants
		end
	
	string_constant_set_procedures: ARRAYED_LIST [PROCEDURE [ANY, TUPLE [STRING_GENERAL]]]
	string_constant_retrieval_functions: ARRAYED_LIST [FUNCTION [ANY, TUPLE [], STRING_32]]
	integer_constant_set_procedures: ARRAYED_LIST [PROCEDURE [ANY, TUPLE [INTEGER]]]
	integer_constant_retrieval_functions: ARRAYED_LIST [FUNCTION [ANY, TUPLE [], INTEGER]]
	pixmap_constant_set_procedures: ARRAYED_LIST [PROCEDURE [ANY, TUPLE [EV_PIXMAP]]]
	pixmap_constant_retrieval_functions: ARRAYED_LIST [FUNCTION [ANY, TUPLE [], EV_PIXMAP]]
	integer_interval_constant_retrieval_functions: ARRAYED_LIST [FUNCTION [ANY, TUPLE [], INTEGER]]
	integer_interval_constant_set_procedures: ARRAYED_LIST [PROCEDURE [ANY, TUPLE [INTEGER_INTERVAL]]]
	font_constant_set_procedures: ARRAYED_LIST [PROCEDURE [ANY, TUPLE [EV_FONT]]]
	font_constant_retrieval_functions: ARRAYED_LIST [FUNCTION [ANY, TUPLE [], EV_FONT]]
	color_constant_set_procedures: ARRAYED_LIST [PROCEDURE [ANY, TUPLE [EV_COLOR]]]
	color_constant_retrieval_functions: ARRAYED_LIST [FUNCTION [ANY, TUPLE [], EV_COLOR]]

	integer_from_integer (an_integer: INTEGER): INTEGER
			-- Return `an_integer', used for creation of
			-- an agent that returns a fixed integer value.
		do
			Result := an_integer
		end

end
