/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_ucl_chime_EiffelBridge */

#ifndef _Included_uk_ac_ucl_chime_EiffelBridge
#define _Included_uk_ac_ucl_chime_EiffelBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_ucl_chime_EiffelBridge
 * Method:    getStringValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_ac_ucl_chime_EiffelBridge_getStringValue
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_ucl_chime_EiffelBridge
 * Method:    getArchetypeNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_ucl_chime_EiffelBridge_getArchetypeNames
  (JNIEnv *, jobject);

/*
 * Class:     uk_ac_ucl_chime_EiffelBridge
 * Method:    setErrorDBDirectoryPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ucl_chime_EiffelBridge_setErrorDBDirectoryPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     uk_ac_ucl_chime_EiffelBridge
 * Method:    setRMSchemaDirectoryPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_ucl_chime_EiffelBridge_setRMSchemaDirectoryPath
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
