/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openehr_archetypes_adl_jni_wrapper_AdlJniWrapper */

#ifndef _Included_org_openehr_archetypes_adl_jni_wrapper_AdlJniWrapper
#define _Included_org_openehr_archetypes_adl_jni_wrapper_AdlJniWrapper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_openehr_archetypes_adl_jni_wrapper_AdlJniWrapper
 * Method:    jarchetype_available
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_openehr_archetypes_adl_1jni_1wrapper_AdlJniWrapper_jarchetype_1available
  (JNIEnv *, jobject);

/*
 * Class:     org_openehr_archetypes_adl_jni_wrapper_AdlJniWrapper
 * Method:    jparse_archetype
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openehr_archetypes_adl_1jni_1wrapper_AdlJniWrapper_jparse_1archetype
  (JNIEnv *, jobject);

/*
 * Class:     org_openehr_archetypes_adl_jni_wrapper_AdlJniWrapper
 * Method:    jstatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_openehr_archetypes_adl_1jni_1wrapper_AdlJniWrapper_jstatus
  (JNIEnv *, jobject);

/*
 * Class:     org_openehr_archetypes_adl_jni_wrapper_AdlJniWrapper
 * Method:    jcreate_c_string_make_from_string_list
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_openehr_archetypes_adl_1jni_1wrapper_AdlJniWrapper_jcreate_1c_1string_1make_1from_1string_1list
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_openehr_archetypes_adl_jni_wrapper_AdlJniWrapper
 * Method:    jarchetype_logical_paths
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_openehr_archetypes_adl_1jni_1wrapper_AdlJniWrapper_jarchetype_1logical_1paths
  (JNIEnv *, jobject, jstring);


#ifdef __cplusplus
}
#endif
#endif
