/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_ucl_chime_EiffelBridge */

#ifndef _Included_uk_ac_ucl_chime_EiffelBridge
#define _Included_uk_ac_ucl_chime_EiffelBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_ucl_chime_EiffelBridge
 * Method:    getStringValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_ac_ucl_chime_EiffelBridge_getStringValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
